language: go
sudo: false
go:
- 1.11.x
services:
  - docker
install:
  - chmod 777 -R "$(pwd)"
  - make dep
jobs:
  include:
    - stage: "Tests"
      name: "Lint"
      script:
        - make lint
        - make test
        - make integration
        - make coverage
        - bash <(curl -s https://codecov.io/bash) -f .coverage/combined.cover.out
    - stage: "Deploy"
      name: "Push To Docker"
      script: curl --request POST "${DOCKER_URL}" >/dev/null 2>&1
      if: branch = master
