[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/asecurityteam/transportd"
  branch = "fine_grain_auth"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
