[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/getkin/kin-openapi"
  version = "0.1.0"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.8.1"

[[constraint]]
  name = "github.com/asecurityteam/serverfull"
  branch = "master"

[[constraint]]
  name = "github.com/asecurityteam/transportd"
  branch = "master"
